version: '3'
services:
  virtuetechpage:
    image: ghcr.io/jonathanmkt/virtuetechpage:latest
    networks:
      - Singanet
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
      labels:
      - traefik.enable=1
      - traefik.http.routers.virtuetechpage.rule=Host(`virtuetech.virtuetech.com.br`)
      - traefik.http.routers.virtuetechpage.entrypoints=websecure
      - traefik.http.routers.virtuetechpage.priority=1
      - traefik.http.routers.virtuetechpage.tls.certresolver=letsencryptresolver
      - traefik.http.routers.virtuetechpage.service=virtuetechpage
      - traefik.http.services.virtuetechpage.loadbalancer.server.port=80
      - traefik.http.services.virtuetechpage.loadbalancer.passHostHeader=true
      placement:
        constraints:
          - node.role == manager
    environment:
      - VITE_API_URL=${VITE_API_URL}
      - VITE_BASE_URL=${VITE_BASE_URL}

networks:
  Singanet:
    external: true
